# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b96b1f43186bd2e3bdf71f53b10f4c03f8cfcd51f28c4903c128e1604ecbb752896269a2c04b96f14f5bd3a326df10f28d57a8d7165f45d668807a30c706bd2b

test:
  secret_key_base: e4a6cfbfb54da7f909bfec1d88d77003b17545dc1bc4ec7a4a54e5980e248d6266e54d47889f2f6324b07b1be787c5504a1d0bcbb745adaf9155032d7fc0a768

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
